version: '3'
services:
  bot:
    container_name: Mephisto-Discord
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/discord-bot
    restart: always
    env_file:
      - .env
